modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="thirdviewonattack"
version="1.0.0"
displayName="Third View On Attack"
authors="Piasop"
description='''
Over-the-shoulder camera combat experience with adaptive transparency and accurate crosshair when fighting mobs.
'''
